### ISSUE TITLE
how about the fps?

### ISSUE THREAD

**Issue by cs-heibao** [BoPang1996/TubeTK#1]
@BoPang1996 
how about the inference time?

**Comment by BoPang1996** [comment]
1.5fps on V100 when stride is 1. Larger stride will lead to higher fps, but there will be some performance loss.

**Comment by cs-heibao** [comment]
@BoPang1996 
Get it, thanks.

**Comment by richard-salaschavez** [comment]
Is the limiting factor the 3D NN architecture? I was hoping it would be able to run a bit faster to work in real time. Either way great work, really enjoyed reading the paper!
