### ISSUE TITLE
Error when changing "forward_frames" parameter from 4 to 2

### ISSUE THREAD

**Issue by mkansy** [BoPang1996/TubeTK#10]
Hi,

I just tried changing the `forward_frames` parameter from 4 to 2. This should, if I understood it correctly, change the maximum number of frames in a tube from 8 to 4. I then ran the preprocessing with this parameter change to get the ground truth Btubes. When I run the training with this parameter change, I get the following error:

<pre>
Rank: 0 Start!
Building TubeTK Model
MOT17 data
==> Training data : 635400
==> Validation data : 5898
Training

  0%| | 0/635400 [00THCudaCheck FAIL file=/pytorch/aten/src/THC/THCGeneral.cpp line=383 error=11 : invalid argument

  0%| | 0/635400 [00
Traceback (most recent call last):
  File "main.py", line 270, in &ltmodule&gt
    main(train_arg, model_arg)
  File "main.py", line 230, in main
    train(model, optimizer, data_loader, sched, tensorboard_writer, max_acc=max_acc, step_start=step)
  File "main.py", line 113, in train
    losses = run_one_iter(model, optimizer, data, scheduler, False)
  File "main.py", line 66, in run_one_iter
    losses = model(imgs, img_metas, return_loss=True, gt_tubes=gt_tubes, gt_labels=gt_labels)
  File "ANACONDA_ENV_PATH/lib/python3.7/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "ANACONDA_ENV_PATH/lib/python3.7/site-packages/torch/nn/parallel/distributed.py", line 376, in forward
    output = self.module(*inputs[0], **kwargs[0])
  File "ANACONDA_ENV_PATH/lib/python3.7/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "USER_PATH/TubeTK/network/tubetk.py", line 86, in forward
    return self.forward_train(img, img_meta, **kwargs)
  File "USER_PATH/TubeTK/network/tubetk.py", line 71, in forward_train
    x = self.extract_feat(img)
  File "USER_PATH/TubeTK/network/tubetk.py", line 63, in extract_feat
    x = self.neck(x)
  File "ANACONDA_ENV_PATH/lib/python3.7/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "USER_PATH/TubeTK/network/fpn.py", line 56, in forward
    laterals[i], scale_factor=2, mode='nearest')
RuntimeError: output with shape [1, 256, 1, 56, 72] doesn't match the broadcast shape [1, 256, 2, 56, 72]
Traceback (most recent call last):
  File "launch.py", line 95, in &ltmodule&gt
    main()
  File "launch.py", line 91, in main
    cmd=process.args)
subprocess.CalledProcessError: Command '['ANACONDA_ENV_PATH/bin/python', '-u', 'main.py', '--local_rank=0', '--batch_size', '1', '--config', './configs/TubeTK_resnet_50_FPN_4frame_1stride.yaml', '--logName', './logs/example_4frame_1stride', '--model_name', 'TubeTK_example_4frame_1stride']' returned non-zero exit status 1.
</pre>

The line numbers might have changed very slightly since the original implementation because I added print statements in some parts. I did not change anything else in the code though.

How do I get the code to work with a different `forward_frames` value? Do I have to change other hyperparameters (e.g. `model_stride`)?

Thanks!

**Comment by BoPang1996** [comment]
The downsampling rate on the temporal dimension is 8 in our implementation. That is, after inputting a video with 8 frames, the final output of the FPN only has one frame. So if you want to input 4 frames, you need to remove one downsampling layer and change the "model_stride" hyperparameter. For example, remove the final downsample layer and change the model_stride to [[2, 8],[4, 16], [4, 32], [4, 64], [4, 128]]

**Comment by mkansy** [comment]
I changed the `model_stride` parameter as recommended by you and removed the final downsample layer by:
- Commenting lines 134 - 135 in network/resnet.py:
`# x = self.layer4(x)`
`# outs.append(x)`
- Changing line 26 of network/tubetk.py to:
`self.neck = FPN(in_channels=[512, 1024], arg=arg)`

It seems to be working now. Thanks!
