### ISSUE TITLE
KeyError: None

### ISSUE THREAD

**Issue by a228949** [BoPang1996/TubeTK#17]
Hello, I encountered the following error when running the code, after debugging I found that the "file_num" in the "tube_iou_matching.py" file was caused by None, I want to ask how to solve it, is it a wrong configuration in the code, or is there a missing configuration file? Hope the question can be answered, thank you!

10:28:28.442851	Frame: 423.0	Tubes: 10	Cur tracks:15	Arch tracks:110
  0%| | 0/1 [00:17<?
multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/root/miniconda3/envs/py38/lib/python3.8/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "demo.py", line 242, in match_video
    matching(tubes, save_path=os.path.join(output_dir, video_name + '.txt'), verbose=True, arg=model_arg)
  File "/root/TubeTK/post_processing/tube_iou_matching.py", line 434, in matching
    final_processing(tracks, save_path, mid_only)
  File "/root/TubeTK/post_processing/tube_iou_matching.py", line 336, in final_processing
    filt_bbox(save_path)
  File "/root/TubeTK/post_processing/tube_iou_matching.py", line 298, in filt_bbox
    res, _ = track_complete(tracks.get_group(tid).values, params[file_num][2])
KeyError: None
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "demo.py", line 379, in <module>
    main(test_arg, model_arg)
  File "demo.py", line 351, in main
    evaluate(model, loader, test_arg, model_arg, output_dir=test_arg.output_dir)
  File "demo.py", line 282, in evaluate
    p.get()
  File "/root/miniconda3/envs/py38/lib/python3.8/multiprocessing/pool.py", line 771, in get
    raise self._value
KeyError: None
Traceback (most recent call last):
  File "/root/TubeTK/launch.py", line 123, in <module>
    main()
  File "/root/TubeTK/launch.py", line 118, in main
    raise subprocess.CalledProcessError(returncode=process.returncode,
subprocess.CalledProcessError: Command '['/root/miniconda3/envs/py38/bin/python', '-u', 'demo.py', '--local_rank=0', '--batch_size=3', '--config', 'configs/TubeTK_resnet_50_FPN_8frame_1stride.yaml', '--video_url', './TubeTK_video', '--output_dir', './vis_video']' returned non-zero exit status 1.

**Comment by a228949** [comment]
@BoPang1996 @liyz15 Can you answer this question? Thank you so much!

**Comment by liyz15** [comment]
Hello, could you please check the value for `save_path`? The tube_iou_matching relies on the name of save_path to decide different parameters.

**Comment by a228949** [comment]
> Hello, could you please check the value for `save_path`? The tube_iou_matching relies on the name of save_path to decide different parameters.

Hello, I checked and found that './vis_video/res/aaa.mp4.txt' is the value for save_path. The command I executed is "python launch.py --nproc_per 1 --training_script demo.py --batch_size=3 --config configs/TubeTK_resnet_50_FPN_8frame_1stride.yaml --video_url ./TubeTK_video --output_dir ./vis_video". Under the 'TubeTK_video' directory, there is only one video named 'aaa.mp4'. @liyz15

**Comment by liyz15** [comment]
Our post processing relies on the filename to determine different parameters for MOT17 task. As you are using custom video, you can try to manually set the params. For example, directly replace `params[file_num]` with `[0, 6, 8]`

**Comment by a228949** [comment]
> Our post processing relies on the filename to determine different parameters for MOT17 task. As you are using custom video, you can try to manually set the params. For example, directly replace with `params[file_num]``[0, 6, 8]`

Sure, I will give it a try using the dataset and run the model. Thank you very much for your assistance.
