### ISSUE TITLE
Tube NMS Implementation with Two Thresholds?

### ISSUE THREAD

**Issue by mkansy** [BoPang1996/TubeTK#4]
Hello, 

First of all, thanks for publishing your code! I am curious about your tube NMS, so I tried finding the implementation as described in the paper with the two thresholds (gamma_1 for the middle frame and gamma_2 for the outside frames) in the repository. In the [configuration](https://github.com/BoPang1996/TubeTK/blob/master/configs/default.py) as well as the [multiclass_nms function](https://github.com/BoPang1996/TubeTK/blob/master/post_processing/tube_nms.py), I only see one threshold ("test_nms_iou_thre") though. 

Could you tell me where I can find the implementation with the two tresholds, or is that not included in the current code?

Thanks!

**Comment by liyz15** [comment]
There are two thresholds in  [cuda_nms function](https://github.com/BoPang1996/TubeTK/blob/5aab0e252bee461ebd07908d6712413b94f0f312/post_processing/tube_nms.py#L119), the first one is for middle frame and the second one is for side. To use different threshold you need to modify the configuration as well as multiclass_nms a little.

We find it sufficient to use same threshold for both mid and side frames, so different thresholds is not included in the open source version, sorry for the inconvenience.

**Comment by mkansy** [comment]
Thanks for the clarification!
