### ISSUE TITLE
About fine tuning pre-trained model

### ISSUE THREAD

**Issue by mumipyonpyon** [BoPang1996/TubeTK#7]
Hi
I tried resuming from the pre-trained model and training on MOT17 for only 20 steps.
The prediction on MOT17 test video became totally wrong.
it looks likes random boxes are predicted.

What I did is
```
python ./pre_processing/get_tubes_MOT17.py

modify tube_limit to 200

python launch.py --nproc_per 1 --training_script main.py --batch_size 1 --config ./configs/TubeTK_resnet_50_FPN_8frame_1stride.yaml --resume --apex
 ```
I save the model at step 0, 10, 20.

Did I do anything wrong?
Or this result is expected? How should I do it correctly?

**Comment by liyz15** [comment]
I just tested evaluation again and the pre-trained model seems fine. Would you mind trying to evaluate directly with `evaluate.py` and without apex?

**Comment by mumipyonpyon** [comment]
My description about the problem seems not clear enough.
When fine tuning, I save the model at step 0(only for checking resuming is successful), 10, 20.
Then I use ```demo.py``` to test the model (without --apex).

The result of model_step0 was very good (the same as the downloaded pre-trained model.).
The result of model_step10 became worse.
The result of model_step20 became very bad.

I will try again and evaluate them with ```evaluate.py```.
Thank you!

**Comment by liyz15** [comment]
The model should be fine if the result of step 0 is good.

It looks like related to apex, our model is not trained with apex and apex is updating fast so we can not guarantee it will work, sorry about that.
Also, batch size 1 with one GPU seems too small, making the training unstable.

**Comment by mumipyonpyon** [comment]
Thank you!
I think you are right. I haven't thought about that.
